apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: merchantos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: merchantos-backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PORT
              value: "5000"
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: merchantos-secrets
                  key: MONGODB_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: merchantos-secrets
                  key: JWT_SECRET
            - name: RAZORPAY_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: merchantos-secrets
                  key: RAZORPAY_KEY_ID
            - name: RAZORPAY_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: merchantos-secrets
                  key: RAZORPAY_KEY_SECRET
            - name: AI_SERVICE_URL
              value: "http://ai-service:8000"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: merchantos
spec:
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
